### ISSUE TITLE
USPSError being raised on 0.64

### ISSUE THREAD

**Issue by J-CMartin** [happyleavesaoc/python-myusps#11]
It looks like the Default driver (phantomjs) is not being setup as default anywhere and if not passed the component is throwing an error:

  File "/config/deps/lib/python3.6/site-packages/myusps/__init__.py", line 170, in _login
    driver = _get_driver(session.auth.driver)
  File "/config/deps/lib/python3.6/site-packages/myusps/__init__.py", line 151, in _get_driver
    raise USPSError('{} not supported'.format(driver_type))

Adding `  driver: phantomjs  `  to configuration.yaml fixes it, but documentation say it should not need to be set.

**Comment by happyleavesaoc** [comment]
This issue should be opened in the HASS repository.
