### ISSUE TITLE
Issues logging in - USPS Website Change?

### ISSUE THREAD

**Issue by nshores** [happyleavesaoc/python-myusps#15]
I noted today that Selenium and PhantomJS or Chrome are failing to login to the website and generate a auth cookie. I am inveatgating now. Example code to show bug.

```
from selenium import webdriver
from selenium.common.exceptions import TimeoutException, WebDriverException
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

HTML_PARSER = 'html.parser'
BASE_URL = 'https://reg.usps.com'
MY_USPS_URL = BASE_URL + '/login?app=MyUSPS'
AUTHENTICATE_URL = BASE_URL + '/entreg/json/AuthenticateAction'
LOGIN_URL = BASE_URL + '/entreg/LoginAction_input?app=Phoenix&appURL=https://www.usps.com/'
DASHBOARD_URL = 'https://informeddelivery.usps.com/box/pages/secure/DashboardAction_input.action'
INFORMED_DELIVERY_IMAGE_URL = 'https://informeddelivery.usps.com/box/pages/secure/'
PROFILE_URL = 'https://store.usps.com/store/myaccount/profile.jsp'
WELCOME_TITLE = 'Welcome | USPS'
LOGIN_TIMEOUT = 10
COOKIE_PATH = './usps_cookies.pickle'
CACHE_PATH = './usps_cache'
ATTRIBUTION = 'Information provided by www.usps.com'

newdriver = webdriver.PhantomJS()
newdriver.get(LOGIN_URL)


username = newdriver.find_element_by_name('username')
username.send_keys('myusername')
password = newdriver.find_element_by_name('password')
password.send_keys('mypassword')
newdriver.find_element_by_id('btn-submit').click()

```

Output shows the title of the page not changing, hence a failed login..

```

In [11]: newdriver.title
Out[11]: 'USPS.com® - Sign In'

```

**Comment by nshores** [comment]
An update to this. I have a working login again after switching to Firefox headless and Selenium 3.6. I will be putting out a pull request shortly to give an idea of how to fix this.

**Comment by brianjking** [comment]
@nshores Now that your PR was merged any help on getting this working on my RaspberryPi Hassbian installation? Thanks!

**Comment by raman325** [comment]
I am running into the same issue as described above using Chromedriver

In doing some testing with the above code posted by @nshores , I noticed that when getting the text of username or password after the send_keys commands are called, the value returned is an empty string. Shouldn't I be able to retrieve the username/password values I just sent?

**Comment by raman325** [comment]
Also is it possible to get PR #16 pushed into PyPI? Looks like the latest version of your module as published there doesn't support Firefox

**Comment by nshores** [comment]
@raman325  This library isn't working anymore due to changes with authentication (Bot detection) on the MyUSPS site.

**Comment by raman325** [comment]
Got it, thanks for the update!

**Comment by nshores** [comment]
> Got it, thanks for the update!

Actually, based on an update to the recent selenium version (3.14) or the USPS website, this is now suddenly working again!

**Comment by hanxubrian** [comment]
> > Got it, thanks for the update!
> 
> Actually, based on an update to the recent selenium version (3.14) or the USPS website, this is now suddenly working again!

sorry I am new selenium developer can you show me what you have done ?
Will you help me ?

**Comment by Bijan-A** [comment]
I am having issues login. I have used selenium `3.141` and even `4.0.0a6.post1` with PhantomJS/Chrome. In all cases, I get:

![image](https://user-images.githubusercontent.com/116760/83607058-684acd00-a52f-11ea-90c1-3ef6ff6373ca.png)
 which is USPS' way of saying 'stop using a bot'.

Can anyone confirm this module still works?

**Comment by nshores** [comment]
It doesn't work anymore. No matter what I have done, I can't keep it working. It's bot detection for sure.

**Comment by Bijan-A** [comment]
I actually figured issue out. Solution can be found [Here](https://stackoverflow.com/questions/33225947/can-a-website-detect-when-you-are-using-selenium-with-chromedriver). Essentially you change chromedriver binary.. all instances of `cdc_` become `xxx_` where xxx is any random 3 digit character

**Comment by katzenbaer** [comment]
[This is a better solution](https://stackoverflow.com/a/52108199/5481276) and using `perl` to replace the `cdc_` worked for me: `perl -pi -e 's/cdc_/dog_/g' /path/to/chromedriver`
