### ISSUE TITLE
Feature request: Informed Delivery

### ISSUE THREAD

**Issue by colinodell** [happyleavesaoc/python-myusps#6]
USPS is rolling out a new feature soon where customers (in select ZIP codes) can see pictures of incoming deliveries: https://informeddelivery.usps.com/box/pages/intro/start.action

Is this something that you'd consider supporting in this library once the feature is made available?

> We are excited to announce that the My USPS application will soon be upgraded to offer you more benefits and convenience.
>
> No action is required from you - you will retain your My USPS benefits, but will also have access to Informed Delivery® notifications, a new, free feature that gives you the ability to see a digital preview of your incoming mail. Informed Delivery allows you to view grayscale images of the exterior, address side of your household’s letter-sized mailpieces* on a computer, tablet, or mobile device. This new feature offers the convenience of seeing what is coming to your mailbox - anytime, anywhere.
>
> Now when you log in to your My USPS account, you will be able to track packages and view a preview of your letter-sized mailpieces in one, integrated dashboard. Your dashboard will display mailpiece images for a seven-day period; you can also opt to receive these images via email notification.

**Comment by happyleavesaoc** [comment]
Pretty neat. I'm sure we could parse out the URL to that image and include it in the package results.

**Comment by happyleavesaoc** [comment]
Supported on the `master` branch.

`mail = myusps.get_mail(session, [optional date, defaults to today])`

**Comment by colinodell** [comment]
Awesome, thank you!
